### ISSUE TITLE
Shadows not working

### ISSUE THREAD

**Issue by alihs** [aarsteinmedia/dotlottie-player-light#5]
[optimized_m2acyje2 (1).lottie.zip](https://github.com/user-attachments/files/17384198/optimized_m2acyje2.1.lottie.zip)

The full version does support shadows, while the light version doesn't render any shadow

**Comment by johanaarstein** [comment]
Have you by any chance added the shadows with After Effects expressions? If so, it won't work with the light version.

**Comment by alihs** [comment]
We did, it didn't work.
Is there a way we could create a 'medium' version like pick and choose from what we'd like.
Its that the lite version is ~500kb while the full version is ~1.9mb (thats tooo much for a javascript)

**Comment by johanaarstein** [comment]
The full bundled version is ~360 KiB, while the lite bundled version is ~210 KiB. To allow for compiler optimization and backwards compatibility both includes esmodule and cjs versions, as well as element schema and typings. These should however not affect the front end. How are you consuming the library?
